var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                  xxx           ",
   "                                                   xx      xx    xx!xx          ",
   "                                    o o      xx                  x!!!x          ",
   "             x                                                   xx!xx          ",
   "                                   xxxxx                          xvx           ",
   "                        o                                                   xx  ",
   "                                          o o                                x  ",
   "  xx                    o                                                  o x  ",
   "  x          ^                           xxxxxx                            o x  ",
   "  x          xxxx       o                                                    x  ",
   "  x  @       xxxx                         <xx>                    xxxxx       x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxx  ",
   "                              x!!!x                  x     x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              xxxxx                  xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
   [ "                      ",
  "                      ",
  "  x               =x  ",
  "  x         o o   |x  ",
  "  x @      xxxxx   x  ",
  "  xxxxx            x  ",
  "      x!!!!!!!!!!!!x  ",
  "      xxxxxxxxxxxxxx  ",
  "                      "],
  ["                                      x!!x             xxx        xxxxxxx                                    x x  ",
   "                                      x!!x                     xxxx     xxxx                                 x x  ",
   "                                      x!!xxxxxxxxxx           xx           xx                                x x  ",
   "                                      xx!!!!!!!!!!xx         xx             xx                               x x  ",
   "                                       xxxxxxxxxx!!x         x                                    o   o   o  x x  ",
   "                                                xx!x         x     o   o                                    xx x  ",
   "                                                 x!x         x                                xxxxxxxxxxxxxxx  x  ",
   "                                                 x|x               x   x                                      =xx  ",
   "                                                                |   |   |  xx      xx    xxxxxxxxxxxxxxxxxxxxxx  ",
   "=                       x                                   =xxx!!!!!!!!!!!xx            v                        ",
   "                                                          xx    xxxx!!!!!xxxx      o                                ",
   "                                               x     xx           xxxxxxx        xxx         xxx                  ",
   "                                               x     x                            x x         x x                  ",
   "          xxxxx                                x     x                             x         x                    ",
   "                        xxxx                   xo    x                xxx     xxx             x                    ",
   "                                               xx    x                                       x                    ",
   "                                  o         x     x        o  o  x   x    xx             xxxx                    ",
   "               xxxxxxx                         x     x               x   x                   x                    ",
   "              xx  o  xx       xxx   xxx        x  o  x     xxxxxx    x   x   xxxx            x                    ",
   "             xx       xx        x o x          x    xx               x   x   x    x          x                    ",
   "     @       x            xx    x   x          x     x               x   x   x      x        x                    ",
   "    xxx      x    xx            x   x          x     x               x   xxxxx   xxxxxx      x                    ",
   "    x x      xxxxxxxxxxxx      xx o xx         x     x  ^    ^       x     o     x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!     x     =     x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxx     x!!!!!!!xx! xxxxxxxxxxxxxxxxx xx  o o  xx                    ",
   "!!!!x x!!!!!!x         x!!!!!x    o         oo       xx!!!!!!xxv                    xx     xx                     ",
   "!!!!x x!!!!!!x         x!!!!!x                     xx!!!!!!xx                        xxxxxxx                      ",
   "!!!!x x!!!!!!x         x!!!!!xx     = xxxxxxxxxxxxxx!!!!!!xx                                                      ",
   "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx                                                       ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx                                                        "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                        o                                                                     ",
   "                                        o                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                       xxx                                                                    ",
   "                                       x x                 !!!        !!!  xxx                                ",
   "                                       x x                 !x!        !x!                                     ",
   "                                     xxx xxx                x          x                                      ",
   "                                      x   x                        x       xxx                                ",
   "                                      x   x                       o o  x      x!!!x                           ",
   "                                      x   x                 xxxxxxxxxxxx       xxx                            ",
   "                                     x  xx      x        o  x                                                ",
   "                                      x   xxxxxxxxx   xxxxxxxx              x x                               ",
   "                                      x   x           x                    x!!!x                              ",
   "                                      x   x         xxx                     xxx                               ",
   "                                     xx   xx          x                                                       ",
   "                                      x   x       <   x            xxx                                        ",
   "                                      x   x        xxxx           x!!!x                                       ",
   "                                      x   x       >   x    xx      xxx       xxx                              ",
   "                                    xxxx    xx          x                     x!!!x                          ",
   "                              o   o   x   x         xxx     x                xx>       <xxx                   ",
   "                                      x   x           x              x                 x!!!x                  ",
   "                             xxx xxx xxx xxx     o o  x!!!!!!!!!!!!!!x                   vx                   ",
   "                             x xxx x x xxx x    oooo      x!!!!!!!!!!!!!!xxx                                  ",
   "                             x             x   xxxxxxxxxxxxxxxxxxxxxxxxxvx                                    ",
   "                             xx           xx                                         xxx                      ",
   "  xxx                 xxxxx   x     x                                               x!!!x                xxx  ",
   "  x x    xxx                  x    xxx                                               xxx                 x x  ",
   "  x                           x    xxx    xxxxxxx                        xxxxx                             x  ",
   "  x              xxx          x           x                              x   x                             x  ",
   "  x                           xx          x                              x x x                             x  ",
   "  x                     xxx            xx x       |xxxx|    |xxxx|     xxx xxx                             x  ",
   "  x                xxx             o o    x                         xx   x         xxx                     x  ",
   "  x               xxxxx       xx          x                             xxx       x!!!x          x         x  ",
   "  x               oxxxo       x    xxx    x                             x x        xxx          xxx        x  ",
   "  x                xxx        xxxxxxxxxxxxx  x oo x    x oo x    x oo  xx xx                    xxx        x  ",
   "  x@                x         x           x!!x    x!!!!x    x!!!!x    xx   xx                    =         x  ",
   "  xxxxxxxxxxxxxxxxxxxxxx!!!xxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                       xxxxx                                                                                   ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                  xxx x       ",
   "                                                                                                      x       ",
   "                                                                                                  xxxxx       ",
   "                                                                                                  x           ",
   "                                                                                                  x xxx       ",
   "                          o                                                                       x x x       ",
   "                                                                                             o o oxxx x       ",
   "                   xxx                                                                                x       ",
   "       !  o  !                                                xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
   "       x     x                                                x   x x   x x   x x   x x   x x   x x           ",
   "       x  o  x            x                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
   "       x     x                                                  x x   x x   x x   x x   x x   x x     x       ",
   "       !  o  !            o                                  xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
   "                                                                                                              ",
   "          o              xxx                              xx                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                      xx                                                      ",
   "         xxxx      xxx         xxx                                                                            ",
   "                                                                                                              ",
   "                          o                                                     x      x                      ",
   "                                                          xx  v  xx                                           ",
   "             xxx         xxx         xxx                                 x                  x                 ",
   "                                                                                                              ",
   "                                                                                                              ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
   "  x         x   x       x   x       x   x                                     x     x                         ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x>                                    x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                               "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
